export const ActionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	SET_CURRENT_PRODUCT: "SET_CURRENT_PRODUCT",
	SET_IS_LOADING: "SET_IS_LOADING",
	SET_IS_LOADING_PRODUCTS: "SET_IS_LOADING_PRODUCTS",
	SET_IS_LOADING_CURRENT_PRODUCT: "SET_IS_LOADING_CURRENT_PRODUCT",
	SET_IS_LOADING_PRODUCT_TRENDS: "SET_IS_LOADING_PRODUCT_TRENDS",
	
}